name: linux-x64
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test262:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y libcppunit-dev cmake
      - run: git clone https://github.com/david-clang/webf-quickjs.git
      - run: cd webf-quickjs && git checkout fix/gitmodules
      - run: cd webf-quickjs && git submodule update --init --recursive
      - run: ls -lah
      - run: cd webf-quickjs && bash scripts/ci.sh
      - run: cd webf-quickjs && cat test262_report.txt
      - run: cd webf-quickjs && cat test262_errors.txt
